# Generated by Django 4.0.1 on 2022-02-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Murojat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('ism', models.CharField(blank=True, max_length=30, null=True)),
                ('fam', models.CharField(blank=True, max_length=30, null=True)),
                ('yosh', models.IntegerField()),
                ('shaxar', models.CharField(max_length=30)),
                ('matn', models.TextField()),
                ('tel', models.CharField(max_length=30)),
                ('tg_id', models.IntegerField()),
            ],
        ),
    ]
